version: '2'
services:
  app:
    build:
      dockerfile: Dockerfile.development
      context: .
    depends_on:
      - mariadb
    volumes:
      - .:/opt/redbook
    volumes_from:
      - gems
    ports:
      - "3000:3000"
  mariadb:
    image: mariadb
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
  gems:
    image: busybox
    volumes:
      - /ruby_gems
