default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: mariadb
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] %>
development:
  <<: *default
  database: redbook_development
test:
  <<: *default
  database: redbook_test
production:
  <<: *default
  database: redbook_production
  username: redbook
  password: <%= ENV['REDBOOK_DATABASE_PASSWORD'] %>
